name: Python Hello World

on:
  push:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3

      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

      - name: Run Hello World
        run: python main.py